/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Dark Theme — Investment Management Design System
        "surface":                    "#051424",
        "surface-dim":                "#051424",
        "surface-bright":             "#2c3a4c",
        "surface-container-lowest":   "#010f1f",
        "surface-container-low":      "#0d1c2d",
        "surface-container":          "#122131",
        "surface-container-high":     "#1c2b3c",
        "surface-container-highest":  "#273647",
        "surface-variant":            "#273647",
        "surface-tint":               "#8bd6b6",
        "on-surface":                 "#d4e4fa",
        "on-surface-variant":         "#bec9c2",
        "inverse-surface":            "#d4e4fa",
        "inverse-on-surface":         "#233143",
        "outline":                    "#89938d",
        "outline-variant":            "#3f4944",
        "background":                 "#051424",
        "on-background":              "#d4e4fa",
        // Primary
        "primary":                    "#8bd6b6",
        "on-primary":                 "#003828",
        "primary-container":          "#065f46",
        "on-primary-container":       "#8bd6b7",
        "inverse-primary":            "#1b6b51",
        "primary-fixed":              "#a6f2d1",
        "primary-fixed-dim":          "#8bd6b6",
        "on-primary-fixed":           "#002116",
        "on-primary-fixed-variant":   "#00513b",
        // Secondary
        "secondary":                  "#b9c7e0",
        "on-secondary":               "#233144",
        "secondary-container":        "#3c4a5e",
        "on-secondary-container":     "#abb9d2",
        "secondary-fixed":            "#d5e3fd",
        "secondary-fixed-dim":        "#b9c7e0",
        "on-secondary-fixed":         "#0d1c2f",
        "on-secondary-fixed-variant": "#3a485c",
        // Tertiary
        "tertiary":                   "#bcc7de",
        "on-tertiary":                "#263143",
        "tertiary-container":         "#495468",
        "on-tertiary-container":      "#bdc8e0",
        "tertiary-fixed":             "#d8e3fb",
        "tertiary-fixed-dim":         "#bcc7de",
        "on-tertiary-fixed":          "#111c2d",
        "on-tertiary-fixed-variant":  "#3c475a",
        // Error
        "error":                      "#ffb4ab",
        "on-error":                   "#690005",
        "error-container":            "#93000a",
        "on-error-container":         "#ffdad6",
      },
      spacing: {
        "xs":        "4px",
        "sm":        "8px",
        "md":        "16px",
        "lg":        "24px",
        "xl":        "32px",
        "gutter":    "24px",
        "margin":    "32px",
        "max-width": "1440px",
        "base":      "4px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        "sm":    "0.125rem",
        "lg":    "0.25rem",
        "xl":    "0.5rem",
        "2xl":   "0.75rem",
        "full":  "9999px",
      },
      fontFamily: {
        "headline-lg":   ["Work Sans", "sans-serif"],
        "headline-md":   ["Work Sans", "sans-serif"],
        "headline-sm":   ["Work Sans", "sans-serif"],
        "body-lg":       ["Work Sans", "sans-serif"],
        "body-md":       ["Work Sans", "sans-serif"],
        "data-tabular":  ["Geist", "monospace"],
        "label-md":      ["Geist", "monospace"],
      },
      fontSize: {
        "headline-lg":  ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md":  ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm":  ["20px", { lineHeight: "1.4", letterSpacing: "0",       fontWeight: "500" }],
        "body-lg":      ["16px", { lineHeight: "1.6", letterSpacing: "0",       fontWeight: "400" }],
        "body-md":      ["14px", { lineHeight: "1.5", letterSpacing: "0",       fontWeight: "400" }],
        "data-tabular": ["14px", { lineHeight: "1",   letterSpacing: "0",       fontWeight: "400" }],
        "label-md":     ["12px", { lineHeight: "1",   letterSpacing: "0.05em",  fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
